/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/data-screen': RouteRecordInfo<'/data-screen', '/data-screen', Record<never, never>, Record<never, never>>,
    '/debug': RouteRecordInfo<'/debug', '/debug', Record<never, never>, Record<never, never>>,
    '/demos/css-showcase': RouteRecordInfo<'/demos/css-showcase', '/demos/css-showcase', Record<never, never>, Record<never, never>>,
    '/demos/performance': RouteRecordInfo<'/demos/performance', '/demos/performance', Record<never, never>, Record<never, never>>,
    '/demos/performance-hub': RouteRecordInfo<'/demos/performance-hub', '/demos/performance-hub', Record<never, never>, Record<never, never>>,
    '/demos/performance1': RouteRecordInfo<'/demos/performance1', '/demos/performance1', Record<never, never>, Record<never, never>>,
    '/demos/performance2': RouteRecordInfo<'/demos/performance2', '/demos/performance2', Record<never, never>, Record<never, never>>,
    '/demos/vue-operations/Cast': RouteRecordInfo<'/demos/vue-operations/Cast', '/demos/vue-operations/Cast', Record<never, never>, Record<never, never>>,
    '/demos/vue-operations/Opencv': RouteRecordInfo<'/demos/vue-operations/Opencv', '/demos/vue-operations/Opencv', Record<never, never>, Record<never, never>>,
    '/demos/vue-operations/vue-operations': RouteRecordInfo<'/demos/vue-operations/vue-operations', '/demos/vue-operations/vue-operations', Record<never, never>, Record<never, never>>,
    '/demos/vue-operations/WebAssembly': RouteRecordInfo<'/demos/vue-operations/WebAssembly', '/demos/vue-operations/WebAssembly', Record<never, never>, Record<never, never>>,
    '/skills/': RouteRecordInfo<'/skills/', '/skills', Record<never, never>, Record<never, never>>,
    '/skills/flutter': RouteRecordInfo<'/skills/flutter', '/skills/flutter', Record<never, never>, Record<never, never>>,
    '/skills/security': RouteRecordInfo<'/skills/security', '/skills/security', Record<never, never>, Record<never, never>>,
    '/skills/test': RouteRecordInfo<'/skills/test', '/skills/test', Record<never, never>, Record<never, never>>,
    '/skills/vue': RouteRecordInfo<'/skills/vue', '/skills/vue', Record<never, never>, Record<never, never>>,
    '/skills/web': RouteRecordInfo<'/skills/web', '/skills/web', Record<never, never>, Record<never, never>>,
  }
}
